export enum UserSingIn {
  LOGOUT = "USER_LOGOUT",

  REQUEST = "USER_DETAIL_REQUEST",
  SUCCESS = "USER_DETAIL_SUCCESS",
  FAIL = "USER_DETAIL_FAIL",
}


export enum UserEdit {
  REQUEST = "USER_EDIT_REQUEST",
  SUCCESS = "USER_EDIT_SUCCESS",
  FAIL = "USER_EDIT_FAIL",
  RESET = "USER_EDIT_RESET",

}
